# ==============================================================================
# FILE: /rent-anything-platform/docker-compose.prod.yml
# ==============================================================================
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rental_backend_prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13-alpine
    container_name: rental_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    restart: always

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: rental_nginx_prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data_prod:
