# ==============================================================================
# FILE: /rent-anything-platform/docker-compose.yml
# ==============================================================================
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rental_backend_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: rental_frontend_dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    container_name: rental_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./env.dev

volumes:
  postgres_data_dev:
